### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by mgrdcm** [heroku/django-heroku#19]
Looks like this is mostly the work of @kennethreitz (THANK YOU!) and of course owned by the Heroku account, but little maintainer activity in the past 7 months.  Is it being maintained or should we stop using it?

**Comment by ddahan** [comment]
In addition, I sent a mail to `support@heroku.com` with the link to this issue.

**Comment by sigmavirus24** [comment]
Yes it is. There has been little maintainer activity because there has been little to do. The project is rather stable to the best of our understanding.

**Comment by mgrdcm** [comment]
Perfect.  Thanks @sigmavirus24!  When I was looking at using it I just saw that there wasn't much activity so thought it might have been abandoned.  I'll integrate it now!  Thanks so much!

**Comment by ddahan** [comment]
I really don't want to be rude to anyone @sigmavirus24, but you say "There has been little maintainer activity because there has been little to do".
Then, if there is little to do, I think the minimum Heroku should do is to follow the few issues and answer them without customers having the need to contact support for that.
This is an official package, recommanded in the official documentation, and Heroku is not a free service with working volunteers.

But thanks anyway for answering us quickly in the end :)
